export {default as Home} from './home'
export {default as ScanQr } from './scan-qr'
export {default as ScanUrl} from './scan-url'
export {default as WifiSecurity} from './wifi-security/wifi-security'
export {default as WifiSecurityDetails} from './wifi-security/wifi-security-details'
export {default as CyberNews} from './cyber-news'
export {default as OtpSecurity} from './otp-security'
export {default as DataBreach} from './data-breach'
export {default as AppPermission} from './app-permission/app-permissions'
export {default as AppPermissionDetails} from './app-permission/app-permission-detail'
export {default as SecurityAdvisor} from './security-advisor/security-advisor'
export {default as ThreatAdvisor} from './threat-advisor'
export {default as AdwareScan} from './adware-scan'
export {default as AppStatistics} from './app-statistics/app-statistics'
export {default as HiddenApps} from './hidden-apps'
