export const enum Paths {
    SplashScreen = 'splashScreen',
    Login = 'login',
    Register = 'register',
    VerifyEmail = 'verifyEmail',
    ForgetPassword = 'forgetPassword',
    Profile = 'profile',
    Contact = 'contact',
    PrivacyPolicy = 'privacyPolicy',
    Home = 'home',
    ScanQr = 'scan-qr',
    ScanUrl = 'scan-url',
    ScanWebUrl = 'scan-web-url',
    ScanPaymentUrl = 'scan-payment-url',
    ScanAppUrl = 'scan-app-url',
    WifiSecurity = 'wifi-security',
    WifiSecurityDetails = 'wifi-security-details',
    CyberNews = 'cyber-news',
    OtpSecurity = 'otp-security',
    DataBreach = 'data-breach',
    AppPermission = 'app-permission',
    AppPermissionDetails = 'app-permission-details',
    SecurityAdvisor = 'security-advisor',
    ThreatAdvisor = 'threat-advisor',
    AdwareScan = 'adware-scan',
    AdsList = 'ads-list',
    AppStatistics = 'app-statistics',
    AppUsageStats = 'app-usage-stats',
    DataUsageStats = 'data-usage-stats',
    ActiveTimeDetails = 'active-time-details',
    AppUpdates = 'app-updates',
    HiddenApps = 'hidden-apps'
  }
  